from enum import Enum

class Race(Enum):
    Aasimar = "Aasimar"
    Dragonborn = "Dragonborn"
    Dwarf = "Dwarf"
    Elf = "Elf"
    Gnome = "Gnome"
    Goliath = "Goliath"
    Halfling = "Halfling"
    Human = "Human"
    Orc = "Orc"
    Tiefling = "Tiefling"
    Goblin = "Goblin"
    Hobgoblin = "Hobgoblin"
    Bugbear = "Bugbear"
    Elemental = "Elemental"
    Goblin = "Goblin"
    Kobold = "Kobold"
    Lizardfolk = "Lizardfolk"
    Magmin = "Magmin"